apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aaron-russell-blog
  description: Personal Gatsby blog deployed on Cloudflare Pages
  annotations:
    github.com/project-slug: aaron-russell/blog
  tags:
    - gatsby
    - contentful
    - cloudflare-pages
    - personal-site
spec:
  type: website
  lifecycle: production
  owner: user:aaron-russell
